BEGIN;

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.dia_diem_cham_cong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code VARCHAR(50) NOT NULL UNIQUE,
    ten_dia_diem VARCHAR(200) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    location extensions.geography(Point, 4326) NOT NULL,
    ban_kinh_met DOUBLE PRECISION NOT NULL DEFAULT 50
        CHECK (ban_kinh_met > 0 AND ban_kinh_met <= 5000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_dia_diem_cham_cong_location
    ON public.dia_diem_cham_cong USING GIST (location);

CREATE TABLE IF NOT EXISTS public.vi_tri_cham_cong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cham_cong BIGINT NOT NULL
        REFERENCES public.cham_cong(id) ON DELETE CASCADE,
    id_dia_diem BIGINT NOT NULL
        REFERENCES public.dia_diem_cham_cong(id) ON DELETE RESTRICT,
    hanh_dong VARCHAR(20) NOT NULL
        CHECK (hanh_dong IN ('CHECK_IN', 'CHECK_OUT')),
    store_code VARCHAR(50) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    location extensions.geography(Point, 4326) NOT NULL,
    accuracy_meters DOUBLE PRECISION NOT NULL CHECK (accuracy_meters > 0),
    distance_meters DOUBLE PRECISION NOT NULL CHECK (distance_meters >= 0),
    allowed_radius_meters DOUBLE PRECISION NOT NULL CHECK (allowed_radius_meters > 0),
    captured_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    is_mocked BOOLEAN NOT NULL DEFAULT FALSE,
    is_within_geofence BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ux_vi_tri_cham_cong_action UNIQUE (id_cham_cong, hanh_dong)
);

CREATE INDEX IF NOT EXISTS ix_vi_tri_cham_cong_attendance
    ON public.vi_tri_cham_cong (id_cham_cong, hanh_dong);

CREATE INDEX IF NOT EXISTS ix_vi_tri_cham_cong_location
    ON public.vi_tri_cham_cong USING GIST (location);

ALTER TABLE public.dia_diem_cham_cong ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vi_tri_cham_cong ENABLE ROW LEVEL SECURITY;

COMMIT;
