BEGIN;

ALTER TABLE public.dia_diem_cham_cong
    ADD COLUMN IF NOT EXISTS configured_accuracy_meters DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS configured_by_employee_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'dia_diem_configured_by_employee_fkey'
          AND conrelid = 'public.dia_diem_cham_cong'::regclass
    ) THEN
        ALTER TABLE public.dia_diem_cham_cong
            ADD CONSTRAINT dia_diem_configured_by_employee_fkey
            FOREIGN KEY (configured_by_employee_id)
            REFERENCES public.nhan_vien(id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.lich_su_dia_diem_cham_cong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dia_diem BIGINT NOT NULL
        REFERENCES public.dia_diem_cham_cong(id) ON DELETE CASCADE,
    store_code VARCHAR(50) NOT NULL,
    changed_by_employee_id BIGINT
        REFERENCES public.nhan_vien(id) ON DELETE SET NULL,
    old_latitude DOUBLE PRECISION,
    old_longitude DOUBLE PRECISION,
    old_radius_meters DOUBLE PRECISION,
    new_latitude DOUBLE PRECISION NOT NULL CHECK (new_latitude BETWEEN -90 AND 90),
    new_longitude DOUBLE PRECISION NOT NULL CHECK (new_longitude BETWEEN -180 AND 180),
    new_radius_meters DOUBLE PRECISION NOT NULL CHECK (new_radius_meters > 0),
    accuracy_meters DOUBLE PRECISION NOT NULL CHECK (accuracy_meters > 0),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_lich_su_dia_diem_store_changed_at
    ON public.lich_su_dia_diem_cham_cong (store_code, changed_at DESC);

ALTER TABLE public.lich_su_dia_diem_cham_cong ENABLE ROW LEVEL SECURITY;

COMMIT;
