BEGIN;

-- Migration: Tạo bảng user_refresh_tokens hỗ trợ duy trì phiên đăng nhập sliding expiration (mô hình Facebook / YouTube)
CREATE TABLE IF NOT EXISTS public.user_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ,
    replaced_by_token_hash CHAR(64),
    device_info VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_user_id
    ON public.user_refresh_tokens (user_id);

CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_token_hash
    ON public.user_refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_expires_at
    ON public.user_refresh_tokens (expires_at);

ALTER TABLE public.user_refresh_tokens ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.user_refresh_tokens FROM anon, authenticated;

COMMIT;
