CREATE TABLE IF NOT EXISTS public.password_reset_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    code_hash char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
    verified_at timestamptz,
    reset_token_hash char(64),
    reset_token_expires_at timestamptz,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_password_reset_codes_expires_at
    ON public.password_reset_codes (expires_at);

REVOKE ALL ON TABLE public.password_reset_codes FROM anon, authenticated;
