using Npgsql;

namespace manage365.Repositories.Auth;

public sealed class PostgresRefreshTokenRepository(NpgsqlDataSource dataSource) : IRefreshTokenRepository
{
    private static bool _tableInitialized;
    private static readonly SemaphoreSlim _initLock = new(1, 1);

    public async Task EnsureTableAsync(CancellationToken cancellationToken = default)
    {
        if (_tableInitialized) return;
        await _initLock.WaitAsync(cancellationToken);
        try
        {
            if (_tableInitialized) return;

            const string sql = """
                CREATE TABLE IF NOT EXISTS public.user_refresh_tokens (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
                    token_hash CHAR(64) NOT NULL UNIQUE,
                    expires_at TIMESTAMPTZ NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    revoked_at TIMESTAMPTZ,
                    replaced_by_token_hash CHAR(64),
                    device_info VARCHAR(255)
                );

                CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_user_id ON public.user_refresh_tokens(user_id);
                CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_token_hash ON public.user_refresh_tokens(token_hash);
                CREATE INDEX IF NOT EXISTS ix_user_refresh_tokens_expires_at ON public.user_refresh_tokens(expires_at);
                """;

            await using var command = dataSource.CreateCommand(sql);
            await command.ExecuteNonQueryAsync(cancellationToken);
            _tableInitialized = true;
        }
        finally
        {
            _initLock.Release();
        }
    }

    public async Task SaveRefreshTokenAsync(
        long userId,
        string tokenHash,
        DateTimeOffset expiresAtUtc,
        string? deviceInfo = null,
        CancellationToken cancellationToken = default)
    {
        await EnsureTableAsync(cancellationToken);

        const string sql = """
            INSERT INTO public.user_refresh_tokens
                (user_id, token_hash, expires_at, created_at, last_used_at, device_info)
            VALUES (@userId, @tokenHash, @expiresAt, now(), now(), @deviceInfo);
            """;

        await using var command = dataSource.CreateCommand(sql);
        command.Parameters.AddWithValue("userId", userId);
        command.Parameters.AddWithValue("tokenHash", tokenHash);
        command.Parameters.AddWithValue("expiresAt", expiresAtUtc);
        command.Parameters.AddWithValue("deviceInfo", (object?)deviceInfo ?? DBNull.Value);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task<UserRefreshToken?> SlideExpirationAsync(
        string tokenHash,
        DateTimeOffset newExpiresAtUtc,
        CancellationToken cancellationToken = default)
    {
        await EnsureTableAsync(cancellationToken);

        const string sql = """
            UPDATE public.user_refresh_tokens
            SET expires_at = @newExpiresAt,
                last_used_at = now()
            WHERE token_hash = @tokenHash
              AND revoked_at IS NULL
              AND expires_at > now()
            RETURNING id, user_id, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by_token_hash, device_info;
            """;

        await using var command = dataSource.CreateCommand(sql);
        command.Parameters.AddWithValue("tokenHash", tokenHash);
        command.Parameters.AddWithValue("newExpiresAt", newExpiresAtUtc);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        return await reader.ReadAsync(cancellationToken) ? ReadToken(reader) : null;
    }

    public async Task<UserRefreshToken?> FindValidTokenAsync(
        string tokenHash,
        CancellationToken cancellationToken = default)
    {
        await EnsureTableAsync(cancellationToken);

        const string sql = """
            SELECT id, user_id, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by_token_hash, device_info
            FROM public.user_refresh_tokens
            WHERE token_hash = @tokenHash
              AND revoked_at IS NULL
              AND expires_at > now()
            LIMIT 1;
            """;

        await using var command = dataSource.CreateCommand(sql);
        command.Parameters.AddWithValue("tokenHash", tokenHash);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        return await reader.ReadAsync(cancellationToken) ? ReadToken(reader) : null;
    }

    public async Task RevokeTokenAsync(
        string tokenHash,
        CancellationToken cancellationToken = default)
    {
        await EnsureTableAsync(cancellationToken);

        const string sql = """
            UPDATE public.user_refresh_tokens
            SET revoked_at = now()
            WHERE token_hash = @tokenHash
              AND revoked_at IS NULL;
            """;

        await using var command = dataSource.CreateCommand(sql);
        command.Parameters.AddWithValue("tokenHash", tokenHash);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task RevokeAllUserTokensAsync(
        long userId,
        CancellationToken cancellationToken = default)
    {
        await EnsureTableAsync(cancellationToken);

        const string sql = """
            UPDATE public.user_refresh_tokens
            SET revoked_at = now()
            WHERE user_id = @userId
              AND revoked_at IS NULL;
            """;

        await using var command = dataSource.CreateCommand(sql);
        command.Parameters.AddWithValue("userId", userId);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static UserRefreshToken ReadToken(NpgsqlDataReader reader) => new(
        reader.GetInt64(0),
        reader.GetInt64(1),
        reader.GetString(2),
        reader.GetFieldValue<DateTimeOffset>(3),
        reader.GetFieldValue<DateTimeOffset>(4),
        reader.GetFieldValue<DateTimeOffset>(5),
        reader.IsDBNull(6) ? null : reader.GetFieldValue<DateTimeOffset>(6),
        reader.IsDBNull(7) ? null : reader.GetString(7),
        reader.IsDBNull(8) ? null : reader.GetString(8));
}
